### ISSUE TITLE
Add common tree methods

### ISSUE THREAD

**Issue by lverweijen** [BR1py/itertree#29]
To make the transition easier from other packages such as anytree, bigtree, it could be convenient to add some common tree methods/properties (that return either a view or iterator):

- `children` (maybe rename constructor parameter `subtree` to children?)
- `ancestors`
- `descendants`
- `leaves`
- `parent` and `root` are already present
- `is_leaf`
- `siblings`

Also different iterators (pre-order, post-order, level-order).
How about `root.deep.preorder()`?

itertree seems to copy the interface of a dict with methods such as `keys()`, `values()` and `items()` but to me these methods aren't immediately obvious when applied to trees, so how about some more tree-like method names instead. Making them aliases for ths dict-like interface could also be an idea.

**Comment by BR1py** [comment]
After the last internal review we desided to go for an implementation which is more "pythonic" as before. That's why the interface of itertree finally is in first case list-like and in second dict-like (but with deep access for nested (tree) structures). The mentioned packages we do not see as a standart. Furthermore you may look in implementaions for trees like in xml or lxml. Which we see more as a standrad (list-like too).
For features already exists we will not provide a second function with same functionality (and we will not rename the "pythonic" list or dict-like methods). We think the interfaces in Python should be kept as small as possible. From our point of view if possible we should not have redundant functions in a class (You may overload the class for renaming proposes).

But from what I understood you do not just ask just for an adaption of the interface. In most cases you ask for additional features (children access and iterators).
I will check the functionalities in the tree objects mentioned and and we willl try to integrate missing functionalities with same naming in the itertree.

Please give me the time to understand the target functions in the other objects. I will give a more detailed answer after this investigation.

**Comment by BR1py** [comment]
I checked the requested functionalities and I can replace most of your questionmarks.
You can use itertools.chain to append the items itself.

`node.leaves `-> `[n for n in mytree if not n]`
`node.is_leave` -> `not mytree`
`PreOrderIter(node) `-> `itertools.chain([mytree],mytree)`
`PostOrderIter(node)` -> `itertools.chain(mytree.iter(up_to_down=False),[mytree])`

Only for the `LevelOrderIter()` method there is no easy counterpart.

I added an example how the iTree object can be overloaded (include LevelOrderIter()):
https://github.com/BR1py/itertree/blob/dev/src/itertree/examples/itree_like_anytree.py

I think it makes sense to extend some functions in itertree in the next version, we are planning:

`ancestors`
`siblings`
`deep.iter_pre_order()`
`deep.iter_post_order()`
`deep.iter_level_order()`

and an additional iterator for level siblings in whole tree:
`deep.iter_level()`

**Comment by BR1py** [comment]
One more remark:
`mytree.value` - is a data object where the user can store any kind of data in the related tree-item (node)
`mytree.values()`  - iterates over those values stored in the children of mytree

**Comment by lverweijen** [comment]
Sounds good. Thanks for the clarification about `value` and `values`.
I would like `is_leaf`, because writing `if node` to check whether something is a leaf is not really obvious to me. I can inherit or write `not len(node)` instead.
My trees also seem a bit easy, because I'm not really using the value property nor do I have multiple nodes with the same tag.
I could probably just ignore these properties and leave them at their default value.

**Comment by lverweijen** [comment]
I came up with my own solution for this problem on https://github.com/lverweijen/AbstractTree/blob/main/examples/itertree_example.py.
This adds an anytree-like interface to itertree and would make it easier to transfer code from e.g. anytree to itertree (or back). It would also add more export options to iTree and make it easier to export it to a mermaid diagram or other tree formats.
Please check it out and feel free to suggest improvements.

I would probably recommend to keep the sequence-like interface to itertree and use this abstract class for convenience and/or portability. My solution could still benefit from making iTree a little friendlier on subclassing (https://github.com/BR1py/itertree/issues/30).

**Comment by BR1py** [comment]
Looks good! Sorry I was very busy and I couldn't update itertree as planned yet. 

There is already a new release candidate prepared in the dev branch. It will allow very easy inheritance from iTree class.

**Comment by BR1py** [comment]
I think issue can be closed.
The new release should allow an easy usage of iTree as a super() class.

And we have a lot of new iteration possiblilities. I guess that any request iteration direction is now available.

Some of the requested methods are even implemented.
